name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: 使用 Nnode.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tsc
      - run: pnpm run lint
      - run: pnpm run test
