name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: 使用 Nnode.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tsc
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build
      - run: cd packages/core && pnpm pack
      - run: cd packages/react && pnpm pack
      - run: cd packages/formula-parser && pnpm pack
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            packages/core/fortune-sheet-core-*.tgz
            packages/react/fortune-sheet-react-*.tgz
            packages/formula-parser/fortune-sheet-formula-parser-*.tgz
      - run: cd packages/core && pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cd packages/react && pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cd packages/formula-parser && pnpm publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
